const URL_EASY_WAITER_SERVER = 'http://localhost:3200';

const URL_CONTROLLER_AUTENTICACAO = `${URL_EASY_WAITER_SERVER}/autenticacao`;
const URL_CONTROLLER_PRODUTO = `${URL_EASY_WAITER_SERVER}/produto`;
const URL_CONTROLLER_COMANDA = `${URL_EASY_WAITER_SERVER}/comanda`;
const URL_CONTROLLER_PEDIDO = `${URL_EASY_WAITER_SERVER}/pedido`;
const URL_CONTROLLER_MESA = `${URL_EASY_WAITER_SERVER}/mesa`;
const URL_CONTROLLER_CATEGORIA = `${URL_EASY_WAITER_SERVER}/categoria`;
const URL_CONTROLLER_CONEXAO = `${URL_EASY_WAITER_SERVER}/conexao`;
const URL_CONTROLLER_ESTABELECIMENTO = `${URL_EASY_WAITER_SERVER}/estabelecimento`;
const URL_CONTROLLER_ARQUIVO = `${URL_EASY_WAITER_SERVER}/arquivo`;

export class EndpointsConstants {

  static readonly ARQUIVO = {
    UPLOAD: URL_CONTROLLER_ARQUIVO.concat('/upload'),
    DOWNLOAD: URL_CONTROLLER_ARQUIVO.concat('/'),
  };

  static readonly AUTENTICACAO = {
    LOGIN: URL_CONTROLLER_AUTENTICACAO,
  };

  static readonly PRODUTO = {
    CADASTRAR: URL_CONTROLLER_PRODUTO,
    ADQUIRIR: URL_CONTROLLER_PRODUTO,
    ADQUIRIR_TODOS: URL_CONTROLLER_PRODUTO.concat('/adquirirTodos'),
    EDITAR: URL_CONTROLLER_PRODUTO,
    EXCLUIR: URL_CONTROLLER_PRODUTO,
  };

  static readonly COMANDA = {
    ADQUIRIR: URL_CONTROLLER_COMANDA,
    ADQUIRIR_TODAS: URL_CONTROLLER_COMANDA.concat('/adquirirTodas'),
    CONFIRMAR_PAGAMENTO: URL_CONTROLLER_COMANDA.concat('/confirmarPagamento')
  };

  static readonly PEDIDO = {
    ADQUIRIR_NAO_FINALIZADOS: URL_CONTROLLER_PEDIDO.concat('/adquirirNaoFinalizados'),
    ATUALIZAR_STATUS: URL_CONTROLLER_PEDIDO.concat('/atualizarStatus'),
    RECUSAR: URL_CONTROLLER_PEDIDO.concat('/recusar'),
  };

  static readonly MESA = {
    ADQUIRIR_POR_ESTABELECIMENTO: URL_CONTROLLER_MESA,
    CADASTRAR: URL_CONTROLLER_MESA,
    EDITAR: URL_CONTROLLER_MESA,
    EXCLUIR: URL_CONTROLLER_MESA,
  };

  static readonly CATEGORIA = {
    ADQUIRIR_POR_ESTABELECIMENTO: URL_CONTROLLER_CATEGORIA,
    CADASTRAR: URL_CONTROLLER_CATEGORIA,
    EDITAR: URL_CONTROLLER_CATEGORIA,
    EXCLUIR: URL_CONTROLLER_CATEGORIA
  };

  static readonly CONEXAO = {
    TESTAR: URL_CONTROLLER_CONEXAO,
  };

  static readonly ESTABELECIMENTO = {
    ADQUIRIR: URL_CONTROLLER_ESTABELECIMENTO,
    EDITAR: URL_CONTROLLER_ESTABELECIMENTO,
  };
}
